### ISSUE TITLE
please make procfile & app.json for deploy to heroku

### ISSUE THREAD

**Issue by todokku** [JisunParkRea/my_djangotube#1]
Hi Jisun ,
please make procfile & app.json & put deploy to heroku button on your exist project repository
waiting for your response with changes commit
finest regards
goodbye

**Comment by JisunParkRea** [comment]
Hi, todokku. Thank you for your attention about my_djangotube project.
However, I'm wondering about who you are
cause I'm very new to github and heroku.
finally, I updated my_djangotube and deploy it to heroku as you want.
warm regards
